### ISSUE TITLE
Okay, it has begun!

### ISSUE THREAD

**Issue by jfrux** [foundrycf/foundry#1]
@russplaysguitar Hop over here and contribute if you're interested.

Two new repos are available, which might move to an gh-organization soon.

@joshuairl / foundry is the platform which is essentially going to be a port of most general Node functionality to CF.

@joshuairl / fpm is the package management piece (of course). :D

Currently, the main thing Foundry is capable of is "require()" which pulls in modules based on a foundry.json file in the root of the module.

You can include modules by directory, or directly by component path.

This replaces the need for "import", "createObject", and "new Blah()".

It works as you would expect, and hasn't been proofed in Windows yet...

Right now it has an internal dependency on UnderscoreCF and Path.
With your permission, I might just pull the functions Path.cfc uses from UnderscoreCF and place them under Array.cfc / Struct.cfc respectively.  I only use like 2 or 3 things from Underscore I believe at this time.  You would, obviously, be a contributing author of this platform and would be properly noted.

I'd love for you to jump in with me and help make this a reality.

Whether this makes an impact on the community or not, I'm using it for all of my components I build simply because it's so much easier to use components by module_name versus a path or directory.

Also, it will have an internal caching mechanism for module references so it only has to traverse / find the component once.

I hope you're interested!

**Comment by russplaysguitar** [comment]
I'll try to help where possible!

Will you be open-sourcing the fpm website, too?

**Comment by jfrux** [comment]
yes
