### ISSUE TITLE
CLI for fpm

### ISSUE THREAD

**Issue by russplaysguitar** [foundrycf/foundry#10]
Are you planning a CLI for fpm? I guess it would have to use curl... (assuming fpm core will be CF).

**Comment by jfrux** [comment]
Planning, yes, but it won't require a server.
It will be using railo-cli when it arrives.

Sent from my iPhone

On Sep 25, 2012, at 11:37 PM, Russ notifications@github.com wrote:

Are you planning a CLI for fpm? I guess it would have to use curl...
(assuming fpm core will be CF).

—
Reply to this email directly or view it on
GitHubhttps://github.com/foundrycf/foundry/issues/10.

**Comment by russplaysguitar** [comment]
railo-cli looks rad. i can't believe adobe didn't include that in cf10. 

so what will be the equivalent of command-line `npm install` in fpm?

**Comment by jfrux** [comment]
`fpm install` of course!

Sent from my iPhone

On Sep 25, 2012, at 11:48 PM, Russ notifications@github.com wrote:

railo-cli looks rad. i can't believe adobe didn't include that in cf10.

so what will be the equivalent of command-line npm install in fpm?

—
Reply to this email directly or view it on
GitHubhttps://github.com/foundrycf/foundry/issues/10#issuecomment-8878177.

**Comment by jfrux** [comment]
Would you have time to port async, archy, rimraf, tmp or mkdirp?
I've created repos for them, just need those modules ported as they are just some of the deps of bower.

**Comment by russplaysguitar** [comment]
I haven't heard of any of those, but I might have some time? It's getting hard to prioritize which of these cf projects to work on!

`fpm install` only works with CLI. What about for non-CLI install?

**Comment by jfrux** [comment]
There will be an API first before the CLI.
You will call it in onapplicationstart like
`fpm.install()`

Sent from my iPhone

On Sep 26, 2012, at 1:04 AM, Russ notifications@github.com wrote:

I haven't heard of any of those, but I might have some time? It's getting
hard to prioritize which of these cf projects to work on!

fpm install only works with CLI. What about for non-CLI install?

—
Reply to this email directly or view it on
GitHubhttps://github.com/foundrycf/foundry/issues/10#issuecomment-8879082.

**Comment by DominicWatson** [comment]
Awesome, my thoughts exactly :) Thanks for adding me to the project btw. I will ~~get~~ make some time to really look at it and catchup soon (then start contributing).

**Comment by jfrux** [comment]
Thanks @DominicWatson, btw, how successful have you been with cfstatic?
I've been aching to do a full port of Sprockets (ruby) over to CF.

My progress is at https://github.com/joshuairl/pinions

I'm looking at adding:
haml-coffee
less
sass
stylus
coffeescript
jade

I'm wanting it to be as clean as possible.

My current codebase is based on Mincer at https://github.com/nodeca/mincer which is a node port of Sprockets in almost every way. haha.

I just like the "directive" based approach to managing all of this but I'd love a MOSTLY CF approach instead of just running some other runtime in the background.

Whateva~

**Comment by DominicWatson** [comment]
CfStatic has been pretty successful I think. Up there on the ColdFusion GitHub projects watch and fork lists. I like it a lot and use a lot. Just so many things you can do with the simple API - I've not heard of stylus or jade, will add them to the list. It does LESS and CoffeeScript pretty effortlessly (from the developer point of view).
