### ISSUE TITLE
Does anyone know if it's possible to reproduce some of the async natures of Node within CF with threads?

### ISSUE THREAD

**Issue by jfrux** [foundrycf/foundry#11]
Trying to think of a good way to do this...

**Comment by russplaysguitar** [comment]
CF threads are asynchronous... what features of node's async system are you looking to reproduce?

**Comment by jfrux** [comment]
Well, I guess just general support for events and eventemitter

**Comment by jfrux** [comment]
Somehow making a unique "thread" for each process or request... and all events called or bound in that thread only refer to that thread when they get called...?  I might not be thinking of this correctly.

**Comment by russplaysguitar** [comment]
Well, by default, multiple simultaneous requests will be processed by different threads in Coldfusion, each only sharing the session and application scope variables (which is why you want to wrap those with cflock).

**Comment by russplaysguitar** [comment]
The closest thing to Nodejs event emitters in CF that I've seen is the Backbone.Events system that I wrote for BackboneCF: https://github.com/russplaysguitar/BackboneCF/blob/master/Backbone.cfc

(Unfortunately I haven't add support for railo yet, but you might be able to copy that sort of eventing system?)

**Comment by jfrux** [comment]
@russplaysguitar I think you could easily port `async` https://github.com/joshuairl/async.
Or at least, get it close...?

It takes your underscorecf functions and makes them async?
Not sure what that might look like in CF but it's a heavy dependency on a lot of current node projects that we're trying to port.  Would be a huge help if this was available to us!

Actually, not all of them, just some of them.

**Comment by jfrux** [comment]
I'm just going to write fpm without async for now until we are sure we can pull that part off.
It just might get nasty if some url's timeout, etc.  we can wrap some threads around some of this if we need to...

**Comment by DominicWatson** [comment]
My understanding is that CF would need to release the thread, without setting a response to the Container, while it waits for asynch operations. Once complete, a new thread would be started and it would send its response to the Container. Not sure that would be possible. Or am I missing the point?

**Comment by jfrux** [comment]
I started porting events from node core.  It's going to work I think.

Sent from my iPhone

On Sep 26, 2012, at 5:33 PM, Dominic Watson notifications@github.com
wrote:

My understanding is that CF would need to release the thread, without
setting a response to the Container, while it waits for asynch operations.
Once complete, a new thread would be started and it would send its response
to the Container. Not sure that would be possible. Or am I missing the
point?

—
Reply to this email directly or view it on
GitHubhttps://github.com/foundrycf/foundry/issues/11#issuecomment-8907232.
