### ISSUE TITLE
Event listener: this is passing, should it?

### ISSUE THREAD

**Issue by jfrux** [foundrycf/foundry#12]
``` js
component name="testAddListeners" extends="mxunit.framework.TestCase" {
  public void function should_work() {

    var gotEvent = false;

    thread name="assertIt" action="sleep" duration="50" {
      assertTrue(gotEvent);
    };

    var e = new core.emitter();

    e.on('maxListeners', function() {
      gotEvent = true;
    });

    // Should not corrupt the 'maxListeners' queue.
    e.setMaxListeners(42);

    e.emit('maxListeners');
    }
}
```

The original test in node events was like this:
Obviously, CF doesn't have a "process.on()" so I did a delayed thread... not sure if this technically proves it's working or not...

``` javascript
var common = require('../common');
var assert = require('assert');
var events = require('events');

var gotEvent = false;

process.on('exit', function() {
  assert(gotEvent);
});

var e = new events.EventEmitter();

e.on('maxListeners', function() {
  gotEvent = true;
});

// Should not corrupt the 'maxListeners' queue.
e.setMaxListeners(42);

e.emit('maxListeners');
```

**Comment by russplaysguitar** [comment]
Why not put the assertion statement into `e.on('maxListeners', function() {` ?

**Comment by DominicWatson** [comment]
Does it fail when you remove `e.on('maxListeners', function() { gotEvent = true; } );`?

**Comment by jfrux** [comment]
@DominicWatson No, but it's because it throws an exception due to `maxListeners` not being an event anymore since I removed the `e.on();`

@russplaysguitar I think the point of this is to call the `assertTrue(gotEvent)` after the event has been bound to simulate async?

**Comment by DominicWatson** [comment]
Ok, does it fail when you change it to this? `e.on('maxListeners', function() { gotEvent = false; } )`

If not, then the test isn't working - if it does, then I don't see why it wouldn't be a valid test.

**Comment by jfrux** [comment]
Ya, it's not a valid test...
I think I just don't quite understand thread's well enough to produce a valid test that emulates the same test as the node version.

**Comment by russplaysguitar** [comment]
May I suggest Ben Nadel's series on threads? http://www.bennadel.com/blog/743-Learning-ColdFusion-8-CFThread-Part-I-Data-Exchange.htm

**Comment by jfrux** [comment]
I think I totally missed the point of this test... z0mg.. sorry guys.

**Comment by DominicWatson** [comment]
My understanding is that any threads that are created will no longer be associated with / be able to 'report back' to the initial user request. Hence the assertion in your thread never being run in the context of the test request. I think that node is fundamentally different here - its asynchronism working within the context of a request (when using server()).

**Comment by jfrux** [comment]
We can work with this, no?

**Comment by jfrux** [comment]
We're just going to have to make it work.  We're going to have to get
creative.  Use threads the way they were intended.

Node isn't great at heavy lifting, I think we can stretch cf to do some
heavy lifting if we do this right.

Sent from my iPhone

On Sep 28, 2012, at 4:04 AM, Dominic Watson notifications@github.com
wrote:

My understanding is that any threads that are created will no longer be
associated with / be able to 'report back' to the initial user request.
Hence the assertion in your thread never being run in the context of the
test request. I think that node is fundamentally different here - its
asynchronism working within the context of a request (when using server()).

—
Reply to this email directly or view it on
GitHubhttps://github.com/foundrycf/foundry/issues/12#issuecomment-8967346.
