### ISSUE TITLE
Make a foundry CLI for initing an app with "foundry"...

### ISSUE THREAD

**Issue by jfrux** [foundrycf/foundry#22]
This might be quite involved given the nature of each type of "CFML" environment / context...
The basis is that we could just ask for the administrator password of the CF server / railo context...
create the mapping for (this) context and take foundry.core and overwrite "component.cfc" for that context.

This would make all other components written in the application able to use "require()" and any other modules that are included in foundry core.

The goal is to make Foundry as simple as possible to integrate as to not cause too much friction for implementing apps in different environments.

EXAMPLE:

```
$: cd ~/projects/my_new_app/
$: foundry init
Please provide your CF administrator password to continue...
> **********
... creating mapping in context...
... creating component.cfc ...
Would you like to create  your app with a Foundry skeleton?
    1. Basic Application
    2. CLI Application
    3. Basic Utility Library
    4. No skeleton.
> _1
```

**Comment by russplaysguitar** [comment]
Sounds interesting, what are the differences between the different skeleton types?

**Comment by jfrux** [comment]
done, piggy backing off of railo env
