### ISSUE TITLE
Wish there was a better option than cfexecute through native java...

### ISSUE THREAD

**Issue by jfrux** [foundrycf/foundry#23]
I want to turn childprocess.cfc into a nice little process spawner like Node has.
I'd love it if it could be simple but effective.

cfexecute does not give us any freedoms that we will need when doing this kind of thing.

We need some clean error responses from our child process, and clean standard responses.

I don't want to have to use a jar or any external libraries to make it work...

I've tried to make childprocess work but can't seem to get anything clean and simple.

**Comment by russplaysguitar** [comment]
What exactly is cfexecute missing?

**Comment by jfrux** [comment]
- No way to define the current working directory.
- No nice way to manage the different types of outputs that may occur such
  as errors and standard...
  I'd like to be able to suppress the exceptions in the console and clean
  them up or use them in some way.

Simply wrapping in try catch doesn't suppress them in console.

I just want some more freedoms.

Sent from my iPhone

On Oct 6, 2012, at 11:47 PM, Russ notifications@github.com wrote:

What exactly is cfexecute missing?

—
Reply to this email directly or view it on
GitHubhttps://github.com/foundrycf/foundry/issues/23#issuecomment-9204851.

**Comment by russplaysguitar** [comment]
Have you thought of using java.lang.runtime.exec via javaloader? Found it in some tips here: http://cfsearching.blogspot.com/2008/01/cfexecute-ffmpeg-and-mencoder-mystery.html

**Comment by jfrux** [comment]
Already did, just not happy with my implm in cf... If I could get it
working better with just cf and no jars I'd be happy

Sent from my iPhone

On Oct 7, 2012, at 1:37 AM, Russ notifications@github.com wrote:

Have you thought of using java.lang.runtime.exec via javaloader? Found it
in some tips here:
http://cfsearching.blogspot.com/2008/01/cfexecute-ffmpeg-and-mencoder-mystery.html

—
Reply to this email directly or view it on
GitHubhttps://github.com/foundrycf/foundry/issues/23#issuecomment-9205367.

**Comment by russplaysguitar** [comment]
What is your OS and CF engine?

**Comment by jfrux** [comment]
Railo Mac, windows too.

During day I work on Mac and evening I test in windows 7

Sent from my iPhone

On Oct 7, 2012, at 2:41 PM, Russ notifications@github.com wrote:

What is your OS and CF engine?

—
Reply to this email directly or view it on
GitHubhttps://github.com/foundrycf/foundry/issues/23#issuecomment-9210844.

**Comment by jfrux** [comment]
Yep, and process builder which is even better but I just don't understand
enough probably to make it useful in cf... Like maybe timing?  I think
those classes are async.

Sent from my iPhone

On Oct 7, 2012, at 1:37 AM, Russ notifications@github.com wrote:

Have you thought of using java.lang.runtime.exec via javaloader? Found it
in some tips here:
http://cfsearching.blogspot.com/2008/01/cfexecute-ffmpeg-and-mencoder-mystery.html

—
Reply to this email directly or view it on
GitHubhttps://github.com/foundrycf/foundry/issues/23#issuecomment-9205367.

**Comment by jfrux** [comment]
Think I might run a CF 10 instance to develop in until I'm done with it so I get a more predictable environment... :-\
Railo 4 beta just has some ghosts that I think might be tricking me up...

**Comment by russplaysguitar** [comment]
Yeah, I had to make the same call for BackboneCF :(
Supporting multiple engines kinda sucks sometimes.
