### ISSUE TITLE
Package foundry with railo-express 4 + cli all in one and register it with brew, and debian package repositories for easy installation

### ISSUE THREAD

**Issue by jfrux** [foundrycf/foundry#27]
This will get you a command-line CFML environment ready + quick dev environment for producing your workhorse CF applications as well as a nice public online registry of CF modules that can be instantly downloaded into your projects via FPM

**Comment by russplaysguitar** [comment]
nice idea

**Comment by jfrux** [comment]
this is done, except for the submitting to the repos... i'm closing it now.
