### ISSUE TITLE
Trying to decide on how to make the library... whether to ditch having module CFC's extending a base... or just use cfscript cfm files?

### ISSUE THREAD

**Issue by jfrux** [foundrycf/foundry#34]
Hmm...

**Comment by russplaysguitar** [comment]
What are the pros/cons?

**Comment by jfrux** [comment]
Meh…
No real "pros" I don't think… lol
In fact, I think it would be more cons than pros, now that I think about it.

Rather just load the modules I need versus load the entire library.

**Comment by jfrux** [comment]
This is a stupid idea, I shouldn't have even posted it...
