### ISSUE TITLE
Create a schema for foundry.json

### ISSUE THREAD

**Issue by russplaysguitar** [foundrycf/foundry#8]
Project maintainers should be able to validate foundry.json against a json-schema (http://json-schema.org/). 

You can use http://www.jsonschema.net to generate a json-schema. Not sure what is the best validation project though...

**Comment by jfrux** [comment]
Config.cfc will validate it.
We could use json schema for them using cfhttp or we could just call validate on install.

**Comment by russplaysguitar** [comment]
I was thinking it would be helpful to have json-schema in the same way that xml has DTDs. That way, as the attributes of foundry.json change through future versions of fpm, older versions of foundry.json will still be valid for the version they were written in.

**Comment by jfrux** [comment]
The version is only valid based on the version of Foundry the user has
installed.

Also, the engines property of the foundry.json will determine its
compatibility.

Semantic version relies heavily on the authors compliance with its rules.

They are simple but important.

My semvar project will be the parser of said versions.

Sent from my iPhone

On Sep 25, 2012, at 4:54 PM, Russ notifications@github.com wrote:

I was thinking it would be helpful to have json-schema in the same way that
xml has DTDs. That way, as the attributes of foundry.json change through
future versions of fpm, older versions of foundry.json will still be valid
for the version they were written in.

—
Reply to this email directly or view it on
GitHubhttps://github.com/foundrycf/foundry/issues/8#issuecomment-8869872.

**Comment by russplaysguitar** [comment]
The main problem that I foresee is that not all projects will be able to maintain currently valid foundry.json files, which could break sub-dependencies. 

For instance, if I create a new project with a valid foundry.json file, but a package that it depends on has an obsolete foundry.json file, then that package's dependencies will not be included, thus breaking my project even though my foundry.json file is completely valid. 

If foundry.json files include a "foundry version" property that can be validated somehow, and fpm maintains support for old foundry.json versions, then the problem described above can be avoided.

**Comment by jfrux** [comment]
Russ,
Honestly, this is how node handles it currently and their package.json
doesn't get modified.  There simply isn't a need.

We won't remove elements from the validation.  We can however deprecate
them.  This wouldn't throw() but would alert them via console that they are
using a deprecated json property.

This make sense?

Sent from my iPhone

On Sep 25, 2012, at 7:11 PM, Russ notifications@github.com wrote:

The main problem that I foresee is that not all projects will be able to
maintain currently valid foundry.json files, which could break
sub-dependencies.

For instance, if I create a new project with a valid foundry.json file, but
a package that it depends on has an obsolete foundry.json file, then that
package's dependencies will not be included, thus breaking my project even
though my foundry.json file is completely valid.

If foundry.json files include a "foundry version" property that can be
validated somehow, and fpm maintains support for old foundry.json versions,
then the problem described above can be avoided.

—
Reply to this email directly or view it on
GitHubhttps://github.com/foundrycf/foundry/issues/8#issuecomment-8873596.

**Comment by jfrux** [comment]
The most important properties are name, version, and dependencies.
These will never change, nor will the standard at which these are defined.

If they for some odd reason change, we would still be forgiving of all older json files.

**Comment by russplaysguitar** [comment]
Okay, sounds like fpm is going to be a pretty close port of npm then?

**Comment by jfrux** [comment]
Debating npm or bower.  Either one will do fine.
I like the generic and simplistic nature of bower.

Plus, dev time on porting bower will be significantly lower.
Also, package names are on first come first serve basis which will work
fine for how small the CF community is.

But bower can also directly install generic links like you we're describing
which I also like.

So think I might begin that process over next day or so.

Sent from my iPhone

On Sep 25, 2012, at 10:41 PM, Russ notifications@github.com wrote:

Okay, sounds like fpm is going to be a pretty close port of npm then?

—
Reply to this email directly or view it on
GitHubhttps://github.com/foundrycf/foundry/issues/8#issuecomment-8877225.

**Comment by russplaysguitar** [comment]
That's true about the package names for CF community. I hadn't heard of bower before, looks cool.
